---
title: Les tests diagnostics (Rmd)
weight: 2
---

<script src="//yihui.org/js/math-code.js"></script>
<!-- Just one possible MathJax CDN below. You may use others. -->
<script async
  src="//mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML">
</script>

# Introduction

Vous avez peut-être vu passer sur le web des articles et/ou vidéos mettant en garde contre la confiance qu'on peut accorder ``en pratique'' à des tests  fiables ``en théorie'' pour diagnostiquer la présence d'une maladie chez un individu\footnote{Ce qui est entendu par "pratique"" et ``théorie'' deviendra clair dans ce qui suit.}. Je voudrais ici contribuer à mieux cerner la portée de ces arguments, en particulier dans le cas d'actualité brûlante du covid-19. Je me baserai pour se faire sur l'excellent article du blog ``Les Zétérinaires'' à ce sujet \citep{zete0420}. Je souhaite de plus expliciter, d'abord de manière intuitive puis mathématique, le raisonnement bayésien qui sous-tend les résultats donnés, de manière à ce que ce document puisse facilement être utilisé dans un cadre pédagogique comme exemple d'application du calcul des probabilités.

# Concepts préalables

Tout d'abord, qu'entend-on par ``fiabilité'' d'un test diagnostic? En réalité, cette notion n'est pas quantifiable par un seul nombre, mais repose sur deux caractéristiques complémentaires et indépendantes d'un test diagnostic:
\begin{itemize}
\item la \emph{sensibilité}, c'est-à-dire la capacité du test à détecter la maladie lorsqu'elle est présente (càd à ne pas ``passer à côté''). La sensibilité est liée à la notion de \emph{faux négatif}: plus la sensibilité est grande, moins il y a de faux négatifs, càd de malades non détectés par le test (``l'alarme sonne toujours'' quand l'individu est malade).
\item la \emph{spécificité}, c'est-à-dire la capacité du test à ne détecter que cette maladie (càd à ne pas la confondre avec une autre affection).  La spécificité est liée à la notion de \emph{faux positif}: plus la spécificité est grande,  moins il y a de faux positifs, càd d'individus sains identifiés erronnément comme malades (``l'alarme ne sonne que'' lorsque l'individu est malade).
\end{itemize}

En termes de probabilités, on peut écrire: 
\begin{align*}
\text{Sensibilité}&=\mathbb{P}(\oplus\vert malade) = 1- \mathbb{P}(\ominus \vert malade) \\
\text{Spécificité}&=\mathbb{P}(\ominus\vert sain) = 1- \mathbb{P}(\oplus \vert sain) 
\end{align*}
où la notation  $\mathbb{P}(A \vert B)$ représente la probabilité de l'événément $A$ étant donné l'événement $B$ (probabilité conditionnelle), le symbole $\oplus$ signifie que le résultat du test est positif, et le symbole $\ominus$ signifie que le résultat du test est négatif.

# Exemples

Considérons le cas d'un test diagnostic dont la sensibilité est de 70\% et la spécificité de 99\%, qui sont les ordres de grandeur pour les tests PCR utilisés pour le diagnostic du covid-19 \citep{zete0420}. %Cela signifie que la probabilité de faux négatif est d'environ 30\% et la probabilité de faux positif est d'environ 1\%. Cela implique-t-il qu'une personne testée négative a 30\% de chances d'être en réalité malade\footnote{Ce qui serait inquiétant dans le cas du covid-19 car ces personnes sont dès lors considérées comme non susceptibles de transmettre la maladie et autorisées à circuler librement dans la population.}, et une personne testée positive a 1\% de chance de ne pas être malade?
Etant donné ces valeurs, on pourrait penser (et l'immense majorité des individus commettent cette erreur lorsqu'ils sont confrontés pour la première fois à la question) que
\begin{itemize}
\item  si le résultat du test est positif, on a 70\% de chances d'avoir effectivement la maladie, et 30\% de chances d'ête un ``faux positif'';
\item si le résultat du test est négatif, on a 99\% de chances de n'être effectivement pas malade, et 1\% de chances d'être un ``faux négatif''.
\end{itemize}
En réalité, ce raisonnement est incorrect, car il revient à confondre la probabilité d'un événément A étant donné un événement B, notée $\mathbb{P}(A \vert B)$, avec la probabilité de l'événement B étant donné l'événement A, $\mathbb{P}(B \vert A)$.  Sans développer plus avant ce constat mathématique (voir section suivante), on peut comprendre pourquoi le raisonnement est erroné sur base d'un exemple simple. En particulier, voici le type d'exemple ``choc''  qui circule sur le web.
%car la probabilité d'être malade (resp. sain) étant donné que le test est positif (resp. négatif) n'est pas la probabilité d'être testé positif (resp. négatif) étant donné qu'on est malade. Même si cette affirmation vous semble incompréhensible de prime abord, il est possible
%Dans les faits, de manière très contre-intuitive,
%et les probabilités réelles s'écartent souvent substantiellement de ces valeurs. 
%En effet, les probabilités qui nous intéressent sont resp. $\mathbb{P}(malade \vert \ominus)$ et $\mathbb{P}(sain \vert \oplus)$ et non resp. $\mathbb{P}(\ominus \vert malade)$ et $\mathbb{P}(\oplus \vert sain)$
%En effet, pour calculer correctement ces probabilités, il faut connaître ce qu'on appelle la probabilité \emph{a priori} d'être malade (que nous noterons $\mathbb{P}(malade)$), et elle dépend des circonstances dans lesquelles on est amené à passer le test. 
%S'il s'agit d'un test mené dans le cadre d'un dépistage massif au sein de la population, sans suspicion particulière d'avoir contracté la maladie, alors la probabilité a priori d'être malade est la \emph{prévalence} de la maladie dans la population, càd la proportion de personnes malades au sein de la population.
%En particulier, voici le type d'exemple ``choc'' qui circule sur le web. 
%Voici pourquoi, sur base du type d'exemple ``choc'' qui circule sur le web. 

Supposons que la prévalence de la maladie dans la population générale soit de 1\%, et que l'individu soit testé dans le cadre d'un dépistage massif, çàd sans suspicion particulière préalable qu'il soit malade. Supposons également que la population en question soit de 10000 individus (ce nombre n'a pas d'importance, il est choisi pour la commodité de calcul). Dans cette population, il y a donc 10000/100=100 individus malades. Etant donné la sensibilité du test, 70 d'entre eux seront testés positivement et 30 d'entre eux négativement. La spécifité de 99\% implique quant à elle que parmi les 9900 individus non-malades, $0,99\times9900=9801$ seront testés négativement et $0,01\times 9900=99$ seront testés positivement.

Intéressons-nous tout d'abord à la probabilité d'être malade lorsqu'on est testé positif. Pour calculer correctement cette probabilité, il faut rapporter le nombre d'individus malades et testés positifs (70) au nombre total d'individus testés positifs (70+99). Ainsi, la probabilité réelle d'être malade en étant testé positif (qu'on appelle la \emph{valeur prédictive positive}, ou VPP) n'est que 70/(169)=0,41 (et non 0,7). Il y a donc 59\% (et non 30\%) de faux positifs.

Les articles/vidéos à ``sensation'' s'arrêtent souvent à ce résultat et en concluent qu'un tel test est inutile, voire contre-productif: dans le cas d'une maladie contagieuse comme le covid-19, il nous conduirait à mettre en quarantaine beaucoup trop d'individus en réalité non porteurs de la maladie.
Cette conclusion est trop hâtive pour plusieurs raisons. 

Tout d'abord, il faut également examiner la probabilité d'être malade lorsqu'on est testé négatif. Le nombre d'invididus malades et négatifs étant égal à 30, et le nombre total d'individus négatifs étant 30+9801, on obtient une probabilité de 30/9831= 0,003. Ainsi, la proportion de faux négatifs est extrêmement faible: 0,3\%. Autrement dit, le risque de considérer comme sains des individus en réalité infectés (beaucoup plus grave que le risque de faux positif, dans le cas d'une maladie contagieuse)  est quasi nul.

Ensuite, et c'est là le plus important, ces résultats changent considérablement si la prévalence de la maladie est plus importante ou si le test n'est pas effectué dans le cadre d'un dépistage massif. En particulier, si on refait le raisonnement précédent en supposant une prévalence de 5\%, on se rend compte que la VPP passe de 0,41 à 0,79 (elle devient donc supérieur à la sensibilité de 0,7). Mais surtout, ce raisonnement ne tient pas compte du fait que la plupart des tests diagnostics ne sont pas effectués ``au hasard'' (c'est le cas seulement des campagnes de dépistage massif), mais sur base d'une suspicion préalable de de contamination, soit parce que l'individu présente des symptômes, soit parce qu'il a été en contact avec une personne contaminée. Or, le calcul effectué sur base de la prévalence n'est pas valable dans ce cas. Le raisonnement pour effectuer le calcul des probabilités correctement dans le cas le plus général est présenté dans la section qui suit.

# Formalisation du raisonnement

Le raisonnement informel présenté dans la section précédente s'exprime mathématiquement par le théorème de Bayes [ref]:

$$\mathbb{P}(A \vert B)= \frac{\mathbb{P}(\text{A et B})} {\mathbb{P}(B) } = \frac{\mathbb{P}(B \vert A)\mathbb{P}(A)} {\mathbb{P}(B) }. $$

Son application au cas des tests diagnostics fournit, pour les probabilités respectivement de faux positif et de faux négatif:

\begin{align*}
\mathbb{P}(sain \vert \oplus) & =  \frac{ \mathbb{P}(\oplus \text{ et sain})} {\mathbb{P}(\oplus) } = \frac{\mathbb{P}(\oplus \vert sain)\mathbb{P}(sain)} {\mathbb{P}(\oplus) } = \frac{(1-\mathbb{P}(\ominus \vert sain)) (1 - \mathbb{P}(malade))} {\mathbb{P}(\oplus) }  \\\\
\mathbb{P}(malade\vert \ominus) & = \frac{\mathbb{P}(\ominus \text{ et malade})} {\mathbb{P}(\ominus) }= \frac{\mathbb{P}(\ominus \vert malade)\mathbb{P}(malade)} {\mathbb{P}(\ominus) } = \frac{(1-\mathbb{P}(\oplus \vert malade))\mathbb{P}(malade)} {\mathbb{P}(\ominus) } 
\end{align*}
où 
$$ \mathbb{P}(\oplus) = \mathbb{P}(\oplus \vert sain)\mathbb{P}(sain) + \mathbb{P}(\oplus \vert malade)\mathbb{P}(malade) $$
et 
$$ \mathbb{P}(\ominus) = \mathbb{P}(\ominus \vert malade)\mathbb{P}(malade) + \mathbb{P}(\ominus \vert sain)\mathbb{P}(sain).
$$

On peut vérifier que ces formules permettent de retrouver les résultats de la section précédente sans spécifier la taille de la population, à condition de remplacer 
$\mathbb{P}(malade)$ par la prévalence de la maladie dans la population.
Cependant, cette probabilité *a priori* d'être malade, $\mathbb{P}(malade)$, n'est égale à la prévalence de la maladie que dans le cas d'un dépistage massif, où l'individu est testé sans indication particulière qu'il soit infecté. Lorsque l'individu est testé sur base d'une suspicion de contamination, il faut substituer à la prévalence la probabilité estimée *a priori* qu'il a été contaminé. Bien sûr, cette probabilité n'est pas évidente à estimer - elle va dépendre des informations à disposition de l'individu et du médecin, et peut-être aussi de leur expérience passée avec la maladie. C'est pourquoi on dit parfois que l'approche bayésienne du calcul des probabilités  est ``subjective''. L'estimation dépend en tout cas crucialement des informations à disposition pour effectuer les calculs.

Pour fixer les idées, si on estime à 50\% la probabilité a priori de l'individu d'être malade, avec les mêmes valeurs de sensibilité et de spécificité que dans la section précédente, la probabilité de faux positif  $\mathbb{P}(sain\vert \oplus)$
ne vaut plus que 1\%, tandis que la probabilité de faux négatif $\mathbb{P}(malade \vert \ominus) $  vaut alors 23\%.

Le graphique ci-dessous illustre cette dépendance très forte des probabilités de faux positif et faux négatif à la probabilité a priori d'être malade.
